name: emailagent
channels:
  - conda-forge

dependencies:
  - python=3.12
  - jinja2
  - pandas
  - cloudpickle
  - jsonpickle
  - bs4
  - pip
  - python-dotenv

pip:
  - google-api-python-client
  - itables
  - request
  - nltk
  - google_auth_oauthlib
  - psycopg2
