dependencies:
  - python=3.12
  - jinja2
  - pandas
  - cloudpickle
  - jsonpickle
  - bs4
  - pip
  - python-dotenv
  - psycopg2
  - google-api-python-client
  - itables
  - request
  - nltk

pip:
  - google_auth_oauthlib
  
