name: emailagent
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - jinja2
  - pandas
  - cloudpickle
  - jsonpickle
  - bs4
  - pip
  - python-dotenv

  # Packages from pip
  - pip:
    - google-api-python-client
    - itables
    - request
